version: "3.6"
services:
  d7mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: d7app
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    expose:
        - "3306"
    volumes:
    - d7mysql:/var/lib/mysql
  
  web:
    build: .
    ports:
     - 8086:80
    volumes:
    - ./sites:/app/sites/

volumes:
  d7mysql: